export const CLEANUP = 'app/TimeKeepingReportPage/CLEANUP';

export const GET_TIMEKEEPING_REPORT = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT';
export const GET_TIMEKEEPING_REPORT_SUCCESS = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_SUCCESS';
export const GET_TIMEKEEPING_REPORT_FAILURE = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_FAILURE';

export const GET_TIMEKEEPING_REPORT_EQUIPMENT = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_EQUIPMENT';
export const GET_TIMEKEEPING_REPORT_EQUIPMENT_SUCCESS = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_EQUIPMENT_SUCCESS';
export const GET_TIMEKEEPING_REPORT_EQUIPMENT_FAILURE = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_EQUIPMENT_FAILURE';

export const GET_TIMEKEEPING_REPORT_LATEEARLY = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_LATEEARLY';
export const GET_TIMEKEEPING_REPORT_LATEEARLY_SUCCESS = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_LATEEARLY_SUCCESS';
export const GET_TIMEKEEPING_REPORT_LATEEARLY_FAILURE = 'app/TimeKeepingPage/GET_TIMEKEEPING_REPORT_LATEEARLY_FAILURE';

export const GET_ABSENT_REPORT = 'app/TimeKeepingPage/GET_ABSENT_REPORT';
export const GET_ABSENT_REPORT_SUCCESS = 'app/TimeKeepingPage/GET_ABSENT_REPORT_SUCCESS';
export const GET_ABSENT_REPORT_FAILURE = 'app/TimeKeepingPage/GET_ABSENT_REPORT_FAILURE';
