/*
 *
 * ProjectDetailPage constants
 *
 */


export const UPDATE_OFFICIALDISPATCH = 'app/Officialdispatch/UPDATE_OFFICIALDISPATCH';
export const UPDATE_OFFICIALDISPATCH_SUCCESS = 'app/Officialdispatch/UPDATE_OFFICIALDISPATCH_SUCCESS';
export const UPDATE_OFFICIALDISPATCH_FAILURE = 'app/Officialdispatch/UPDATE_OFFICIALDISPATCH_FAILURE';


export const UPLOAD_CREATDOCUMENTARY = 'app/CreatDocumentary/UPLOAD_CREATDOCUMENTARY';
export const UPLOAD_CREATDOCUMENTARY_SUCCESS = 'app/CreatDocumentary/UPLOAD_CREATDOCUMENTARY_SUCCESS';
export const UPLOAD_CREATDOCUMENTARY_FAILURE = 'app/CreatDocumentary/UPLOAD_CREATDOCUMENTARY_FAILURE';



export const CLEANUP = 'app/Officialdispatch/CLEANUP';
