
export const DETECTION_OPTIONS = [
    {
        name: 'cmnd',
        title: 'CMND',
    },
    {
        name: 'dkkd',
        title: 'Đăng ký kinh doanh',
    },
    {
        name: 'sohong',
        title: 'Chứng nhận quyền sử dụng đất',
    },
    {
        name: 'hc',
        title: 'Họ chiếu',
    },
]

export const DIC = {
    "cmnd": {
        "Họ và tên": "name",
        "Họ tên": "name",
        "Họ và tên / Full name": "name",
        "id": "id_card",
        "Số / No": "id_card",
        "Ngày, tháng, năm sinh": "dob",
        "Sinh ngày": "dob",
        "Ngày sinh / Date of birth": "dob",
        "Giới tính": "sex",
        "Giới tính / Sex": "sex",
        "Quốc tịch": "nationality",
        "Quốc tịch / Nationality": "nationality",
        "Quê quán": "poo",
        "Quê quán / Place of origin": "poo",
        "Nguyên quán": "poo",
        "Nơi thường trú": "por",
        "Nơi thường trú / Place of residence": "por",
        "Nơi ĐKHK thường trú": "por",
        "Có giá trị đến": "doe",
        "Có giá trị đến / Date of expiry": "doe",
        "Đặc điểm nhận dạng": "pi",
        "Dấu vết riêng và dị hình": "pi",
        "Đặc điểm nhận dạng / Personal identification": "pi",
        "Ngày làm CMND": "dop",
        "Ngày, tháng, năm / Date, month, year": "dop",
        "Địa điểm làm CMND": "poi",
        "Giám đốc CA": "poi",
    },
    "hc": {
        "Họ và tên / Full name": "name",
        "Số hộ chiếu / Passport N": "passport_id",
        "Số GCMND / ID card N": "id_card",
        "Ngày sinh / Date of birth": "dob",
        "Giới tính / Sex": "sex",
        "Loại / Type": "type",
        "Mã số / Code": "code",
        "Quốc tịch / Nationality": "nationality",
        "Ngày cấp / Date of issue": "dop",
        "Có giá trị đến / Date of expiry": "doe",
        "Nơi cấp / Place of issue": "poi",
        "Nơi sinh / Place of birth": "dob",
    },
    "dkkd": {
        "Tên công ty viết bằng tiếng Việt": "name_VN",
        "Tên công ty viết bằng tiếng nước ngoài": "name_other",
        "Tên công ty viết tắt": "name_code",
        "Địa chỉ trụ sở chính": "addr",
        "Điện thoại": "phone_number",
        "Email": "email",
        "Website": "website",
        "Vốn điều lệ": "equity",
        "Mã số doanh nghiệp": "company_code",
        "Đăng ký lần đầu": "dof",
        "Họ và tên": "incharge",
        "Giới tính": "sex",
        "Chức danh": "title",

        "Sinh ngày": "dob",
        "Loại giấy tờ pháp lý của cá nhân": "id_def",
        "Ngày cấp": "Ngày cấp",
        "Địa chỉ thường trú": "incharge_addr",
        "Địa chỉ liên lạc": "incharge_addr_now",
    },
    "sohong": {
        "id": "id_def",
        "tên ông": "name_mr",
        "Năm sinh ông": "dob_mr",
        "id ông": "id_card_mr",
        "Địa chỉ ông": "addr_mr",
        "tên bà": "name_mrs",
        "Năm sinh bà": "dob_mrs",
        "id bà": "id_card_mrs",
        "Địa chỉ bà": "addr_mrs",
        "Thửa đất số": "id_place",
        "Tờ bản đồ số": "id_map",
        "Địa chỉ": "addr_def",
        "Diện tích": "vacant",
        "Mục đích sử dụng": "objective",
        "Thời hạn sử dụng": "datetime",
        "Nguồn gốc sử dụng": "source",
        "Diện tích sàn": "vacant_house_size",
        "Cấp (Hạng)": "level_house",
        "Thời hạn sở hữu": "datetime_house",
        "Ghi chú": "note",
        "Địa điểm": "place_def",
        "Ngày, tháng, năm": "datetime_place",
        "Nội dung thay đổi và cơ sở pháp lý": "change_content",
    }
};