export const GET_ADVANCE_REQUIRE = 'app/InTernalFinance/GET_ADVANCE_REQUIRE';
export const GET_ADVANCE_REQUIRE_SUCCESS='app/InTernalFinance/ GET_ADVANCE_REQUIRE_SUCCESS';
export const GET_ADVANCE_REQUIRE_FAILURE='app/InTernalFinance/ GET_ADVANCE_REQUIRE_FAILURE'