export const CLEANUP = 'app/EmployeeReportPage/CLEANUP';

export const GET_EMPLOYEE_REPORT_AGE = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_AGE';
export const GET_EMPLOYEE_REPORT_AGE_SUCCESS = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_AGE_SUCCESS';
export const GET_EMPLOYEE_REPORT_AGE_FAILURE = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_AGE_FAILURE';

export const GET_EMPLOYEE_REPORT_BIRTH = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_BIRTH';
export const GET_EMPLOYEE_REPORT_BIRTH_SUCCESS = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_BIRTH_SUCCESS';
export const GET_EMPLOYEE_REPORT_BIRTH_FAILURE = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_BIRTH_FAILURE';

export const GET_EMPLOYEE_REPORT_GENDER = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_GENDER';
export const GET_EMPLOYEE_REPORT_GENDER_SUCCESS = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_GENDER_SUCCESS';
export const GET_EMPLOYEE_REPORT_GENDER_FAILURE = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_GENDER_FAILURE';

export const GET_EMPLOYEE_REPORT_SKILL = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_SKILL';
export const GET_EMPLOYEE_REPORT_SKILL_SUCCESS = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_SKILL_SUCCESS';
export const GET_EMPLOYEE_REPORT_SKILL_FAILURE = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_SKILL_FAILURE';

export const GET_EMPLOYEE_REPORT_CONTRACT = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_CONTRACT';
export const GET_EMPLOYEE_REPORT_CONTRACT_SUCCESS = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_CONTRACT_SUCCESS';
export const GET_EMPLOYEE_REPORT_CONTRACT_FAILURE = 'app/TimeKeepingPage/GET_EMPLOYEE_REPORT_CONTRACT_FAILURE';



//api/hrmEmployee/report-hrm-count-by-org


export const GET_HRMEMPLOYEE_REPORT_HRM_COUNT = 'app/EmployeeReportPage/GET_HRMEMPLOYEE_REPORT_HRM_COUNT';
export const GET_HRMEMPLOYEE_REPORT_HRM_COUNT_SUCCESS = 'app/EmployeeReportPage/GET_HRMEMPLOYEE_REPORT_HRM_COUNT_SUCCESS';
export const GET_HRMEMPLOYEE_REPORT_HRM_COUNT_FAILURE = 'app/EmployeeReportPage/GET_HRMEMPLOYEE_REPORT_HRM_COUNT_FAILURE';

