/*
 *
 * CrmPage constants
 *
 */

export const GET_BUSINESS_OPPORTUNITIES = 'app/CrmPage/GET_BUSINESS_OPPORTUNITIES';
export const GET_BUSINESS_OPPORTUNITIES_SUCCESS = 'app/CrmPage/GET_BUSINESS_OPPORTUNITIES_SUCCESS';
export const GET_BUSINESS_OPPORTUNITIES_FAILURE = 'app/CrmPage/GET_BUSINESS_OPPORTUNITIES_FAILURE';

export const GET_BUSINESS_OPPORTUNITY = 'app/CrmPage/GET_BUSINESS_OPPORTUNITY';
export const GET_BUSINESS_OPPORTUNITY_SUCCESS = 'app/CrmPage/GET_BUSINESS_OPPORTUNITY_SUCCESS';
export const GET_BUSINESS_OPPORTUNITY_FAILURE = 'app/CrmPage/GET_BUSINESS_OPPORTUNITY_FAILURE';

export const UPDATE_BUSINESS_OPPORTUNITY = 'app/CrmPage/UPDATE_BUSINESS_OPPORTUNITY';
export const UPDATE_BUSINESS_OPPORTUNITY_SUCCESS = 'app/CrmPage/UPDATE_BUSINESS_OPPORTUNITY_SUCCESS';
export const UPDATE_BUSINESS_OPPORTUNITY_FAILURE = 'app/CrmPage/UPDATE_BUSINESS_OPPORTUNITY_FAILURE';

export const DELETE_BUSINESS_OPPORTUNITY = 'app/CrmPage/DELETE_BUSINESS_OPPORTUNITY';
export const DELETE_BUSINESS_OPPORTUNITY_SUCCESS = 'app/CrmPage/DELETE_BUSINESS_OPPORTUNITY_SUCCESS';
export const DELETE_BUSINESS_OPPORTUNITY_FAILURE = 'app/CrmPage/DELETE_BUSINESS_OPPORTUNITY_FAILURE';

export const CLEANUP = 'app/CrmPage/CLEANUP';
