export const CLEANUP = 'app/TimeKeepingPage/CLEANUP';

export const GET_TIMEKEEPING_HISTORY_DATA = 'app/TimeKeepingPage/GET_TIMEKEEPING_HISTORY_DATA';
export const GET_TIMEKEEPING_HISTORY_DATA_SUCCESS = 'app/TimeKeepingPage/GET_TIMEKEEPING_HISTORY_DATA_SUCCESS';
export const GET_TIMEKEEPING_HISTORY_DATA_FAILURE = 'app/TimeKeepingPage/GET_TIMEKEEPING_HISTORY_DATA_FAILURE';

export const GET_TIMEKEEPING_BOARD_DATA = 'app/TimeKeepingPage/GET_TIMEKEEPING_BOARD_DATA';
export const GET_TIMEKEEPING_BOARD_DATA_SUCCESS = 'app/TimeKeepingPage/GET_TIMEKEEPING_BOARD_DATA_SUCCESS';
export const GET_TIMEKEEPING_BOARD_DATA_FAILURE = 'app/TimeKeepingPage/GET_TIMEKEEPING_BOARD_DATA_FAILURE';

export const GET_TIMEKEEPING_DAYOFFS_DATA = 'app/TimeKeepingPage/GET_TIMEKEEPING_DAYOFFS_DATA';
export const GET_TIMEKEEPING_DAYOFFS_DATA_SUCCESS = 'app/TimeKeepingPage/GET_TIMEKEEPING_DAYOFFS_DATA_SUCCESS';
export const GET_TIMEKEEPING_DAYOFFS_DATA_FAILURE = 'app/TimeKeepingPage/GET_TIMEKEEPING_DAYOFFS_DATA_FAILURE';

export const GET_TIMEKEEPING_PAYCHECK = 'app/TimeKeepingPage/GET_TIMEKEEPING_PAYCHECK';
export const GET_TIMEKEEPING_PAYCHECK_SUCCESS = 'app/TimeKeepingPage/GET_TIMEKEEPING_PAYCHECK_SUCCESS';
export const GET_TIMEKEEPING_PAYCHECK_FAILURE = 'app/TimeKeepingPage/GET_TIMEKEEPING_PAYCHECK_FAILURE';

export const GET_ALL_SALARY_FORMULA = 'app/ConfigSalaryPage/GET_ALL_SALARY_FORMULA';
export const GET_ALL_SALARY_FORMULA_SUCCESS = 'app/ConfigSalaryPage/GET_ALL_SALARY_FORMULA_SUCCESS';
export const GET_ALL_SALARY_FORMULA_FAILURE = 'app/ConfigSalaryPage/GET_ALL_SALARY_FORMULA_FAILURE';